<Project>
  <PropertyGroup>
    <Version>0.0.1</Version>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PackageProjectUrl>https://github.com/StefH/mcpserver.ThinQConnect</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/StefH/mcpserver.ThinQConnect</RepositoryUrl>
    <ApplicationIcon>../../resources/icon.ico</ApplicationIcon>
    <Copyright>Copyright © Stef Heyenrath</Copyright>
    <Authors>Stef Heyenrath</Authors>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>PackageReadme.md</PackageReadmeFile>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../../PackageReleaseNotes.txt"))</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../resources/icon.png" Pack="true" PackagePath="" />
    <None Include="PackageReadme.md" Pack="true" PackagePath="" Link="PackageReadme.md" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>